### ISSUE TITLE
Nice to see a project with the same name as mine 😜

### ISSUE THREAD

**Issue by VoidmatrixHeathcliff** [craftersmine/EtherEngine#2]
It's exciting to see a project with the same name as mine appear on GitHub, and nothing is more exciting than to see the author of this project also keen on Lua. I sincerely invite you to participate in my ugly project, although it is still a childish child, and most of the documents are written in Chinese. Translation is still in progress, but I believe that there is nothing more convenient for programmers to communicate than code.😋
Venture to contact, I hope my poor English did not disturb you.

My project address link: [https://github.com/VoidmatrixHeathcliff/EtherEngine](https://github.com/VoidmatrixHeathcliff/EtherEngine)

We look forward to your reply ~

**Comment by craftersmine** [comment]
I currently writing a diploma work, so I don't have much time. Also because I working on diploma work, I have other project for it.

About EtherEngine, I don't think I will return to this project at it's current stage, maybe it will be rewritten from scratch, I don't know. But if you want, you can contribute to this project

Thank you for invitation
